spring:
  cloud:
    consul:
      host: 39.106.144.70
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        tags: urlprefix-/client
        prefer-ip-address: true
  application:
    name: applica-client

server:
  port: 8888