spring:
  cloud:
    consul:
      host: 47.96.188.139
      port: 8003
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        tags: urlprefix-/server
        prefer-ip-address: true

  application:
    name: server

server:
  port: 8777